#!/usr/bin/env bash
# A bashh script that transfers a file from our client to a server using cmd-line arguments

if [ $# -lt 4 ]
then 
  echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
  scp -i "$4" -o StrictHostKeyChecking=no "$1" "$3@$2":~/
fi
