#!/usr/bin/env bash
# A script that configures nginx server for /redirect_me to redirect to another page
sudo apt-get -y update
sudo apt-get -y install nginx
sudo sed -i '/listen 80 default_server/a rewrite ^/redirect_me https://www.youtube.com/ permanent;' /etc/nginx/sites-available/default
sudo service nginx restart
