#!/usr/bin/env bash
#this script  pings an IP address passed as an argument 5 times and display message if no argument is passed
if [ "$1" ];
then
ping -c 5 "$1"
else
echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
fi
