#!/usr/bin/env bash
#this script displays the content of the file /etc/passwd, using the while loop and  IFS

while IFS=':' read -r username passwd uid gid info home bashshell;
 do
echo "The user $username is part of the $gid gang,"\
 "lives in $home and rides $bashshell."\
 "$uid's place is protected by the passcode $passwd,"\
 "more info about the user here: $info"
done < /etc/passwd
