#!/usr/bin/env bash
# This script that displays Best School 10 times, but for the 9th iteration, displays Best School and then Hi on a new line
i=1
while [ $i -le 11 ]
do
 if [ $i != 10 ]; then
    echo "Best School"
else
    echo "Hi"
fi
 
 ((i++))
done
