#!/usr/bin/env bash
# this script that loops from 1 to 10
x=1
while [ $x -le 10 ]
do
if [ $x = 4 ]; then
 echo "bad luck"
elif [ $x = 8 ]; then
 echo "good luck"
else
 echo "Best School"
fi
((x++))
done
