#!/usr/bin/env bash
#this script  localhost ip to 127.0.0.2 and  facebook.com ip to 8.8.8.8
cp /etc/hosts ~/hosts.new
echo "127.0.0.2    localhost" > ~/hosts.new
echo "8.8.8.8      facebook.com" >> ~/hosts.new
cp -f ~/hosts.new /etc/hosts
